### ISSUE TITLE
Unexpected identifier error

### ISSUE THREAD

**Issue by ahmad-reza619** [JumpyJacko/manga-cli#4]
I got an error at this line, saying it's a SyntaxError, this probably due to my version of node, i'm using node 14.17.6

https://github.com/JumpyJacko/manga-cli/blob/f8c70013f23d87c6f187b6c75a18d5a1644fb53c/src/modules/fetch-manga-by-title.js#L17

What version of node did you use?

**Comment by JumpyJacko** [comment]
I'm using Node v17.3.0.

**Comment by ahmad-reza619** [comment]
If that's the case, i think we should mention that in the readme, to use node >17

**Comment by JumpyJacko** [comment]
Does using node >17 fix the problem?

**Comment by ahmad-reza619** [comment]
> Does using node >17 fix the problem?

yes it is, but if you want to support other node version, i suggest to delete the assert.
so the import would look like this
```js
import options from '../options.json';
```

I'll gladly open PR for this

**Comment by JumpyJacko** [comment]
I tried using it without, but without it, it didn't let me access the .json

**Comment by ahmad-reza619** [comment]
@JumpyJacko have you tried switching node version before tried to import options without assert?

**Comment by JumpyJacko** [comment]
No, I should probably do that, sorry about that. Completely forgot about trying that.

**Comment by JumpyJacko** [comment]
Fixed the issue because I used node 16 and removed assert
