### ISSUE TITLE
First (or first couple) pages corrupt and can't be opened with feh

### ISSUE THREAD

**Issue by JumpyJacko** [JumpyJacko/manga-cli#5]
Definitely a problem with curl, will have to try a different fetch method, like wget.

**Comment by ahmad-reza619** [comment]
I also had issues when downloading the pages with curl

**Comment by ahmad-reza619** [comment]
![Screen Shot 2022-01-19 at 10 21 31](https://user-images.githubusercontent.com/52902060/150057953-286b8854-6915-4a05-a639-39187e41d5d7.png)
here is the screenshot of the error, i'm using mac btw

**Comment by JumpyJacko** [comment]
Fixed with update, details in [this commit](https://github.com/JumpyJacko/manga-cli/commit/0c221cee1d3e076067fa18d0a690b497320482c2).
